# Introdución a Julia:

<p align="center">
<img src="img/logo.svg"
     alt="Logo de Julia"
     style="float: left; margin-right: 10px; width: 50%;" />
</p>

Accesos directos del cuaderno:

- Control + Enter: Ejecuta la celda actual
- Shift + Enter: Ejecuta la celda actual y pasa a la siguiente

Esto es una celda de texto (Markdown).

In [1]:
# Esto es una celda de procesamiento
1 + 1

2

## Documentación oficial de Julia:

https://docs.julialang.org/en/v1/index.html

## El primer programa

In [2]:
println("Hola mundo")

Hola mundo


In [3]:
"Hola mundo"

"Hola mundo"

## Expresiones aritmeticas

In [4]:
103 + 2

105

In [5]:
103 - 3

100

In [6]:
103 * 2

206

In [7]:
103^2

10609

In [8]:
103 / 2

51.5

Todos los operadores:
https://docs.julialang.org/en/v1/manual/mathematical-operations/#Arithmetic-Operators-1

## Tipos de datos

In [9]:
Sys.WORD_SIZE

64

In [10]:
typeof(105)

Int64

In [11]:
typeof(51.5)

Float64

In [12]:
typeof("Hola mundo")

String

In [13]:
typeof(1_000_000)

Int64

In [14]:
typeof(true)

Bool

- Int : Numeros enteros
- Float : Numeros con punto decimal
- String : Cadenas de texto
- Bool : Valores de verdadero o falso

### Enteros

In [15]:
5 + 5

10

In [16]:
entero_max = typemax(Int64)

9223372036854775807

In [17]:
entero_max + 1

-9223372036854775808

In [18]:
BigInt(entero_max) + 1

9223372036854775808

### Flotantes

In [19]:
1000.0

1000.0

In [20]:
1.0e3

1000.0

In [21]:
10/2

5.0

In [22]:
typeof(Inf)

Float64

In [23]:
10/0

Inf

In [24]:
isinf(2.0)

false

In [25]:
isinf(10/0)

true

In [26]:
typeof(NaN)

Float64

In [27]:
0/0

NaN

In [28]:
isnan(2.0)

false

In [29]:
isnan(0/0)

true

## Strings

In [30]:
"Hola mundo!"

"Hola mundo!"

In [31]:
length("Hola mundo!")

11

In [32]:
"Hola mundo!"[6:10]

"mundo"

In [33]:
"Hola mundo!"[6:end]

"mundo!"

In [34]:
"Hola mundo!" * " ¿Cómo Estás?"

"Hola mundo! ¿Cómo Estás?"

In [35]:
repeat("Hola ", 2)

"Hola Hola "

### Booleanos

In [36]:
true

true

In [37]:
false

false

#### Comparasiones Numericas

In [38]:
10 > 5

true

In [39]:
5 == 5

true

In [40]:
5 != 5

false

In [41]:
4 >= 5

false

In [42]:
isnan(2.0)

false

## Variables

In [43]:
x = 2
x

2

In [44]:
x

2

In [45]:
x + 2

4

In [46]:
ans + 2

6

In [47]:
y = 3

z = x + y

z

5

In [48]:
z = 2

2

In [49]:
valor = 20

20

In [50]:
valor_dollar = 20.0

20.0

In [51]:
こんにちは世界 = "Hola mundo en japonés"

こんにちは世界

"Hola mundo en japonés"

In [52]:
α = 0.5
α * 2

1.0

In [53]:
radio = 5
area = π * radio^2

78.53981633974483

In [54]:
ℯ

ℯ = 2.7182818284590...

In [55]:
if = 3

LoadError: syntax: unexpected "="

In [56]:
2da_variable = 2

LoadError: syntax: "2" is not a valid function argument name around In[56]:1

## Estructuras de datos

### Tuplas

In [57]:
tup = (3.0, x, 0.8, 1.9)

(3.0, 2, 0.8, 1.9)

In [58]:
typeof(tup)

Tuple{Float64, Int64, Float64, Float64}

In [59]:
a,b,c = (1,3,5)

a

1

### Arreglo

In [60]:
a1 = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [61]:
a2 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [62]:
a3 = [5 10 3 ; 7 8 6]

2×3 Matrix{Int64}:
 5  10  3
 7   8  6

In [63]:
a4 = [5 10 3 ; 7.0 8 6]

2×3 Matrix{Float64}:
 5.0  10.0  3.0
 7.0   8.0  6.0

In [64]:
a3 + a4

2×3 Matrix{Float64}:
 10.0  20.0   6.0
 14.0  16.0  12.0

In [65]:
a5 = [5 10 3 ; 7 8 6 ; 1 2 3]

3×3 Matrix{Int64}:
 5  10  3
 7   8  6
 1   2  3

In [66]:
a3 * a5

2×3 Matrix{Int64}:
 98  136  84
 97  146  87

In [67]:
a5 * a3

LoadError: DimensionMismatch("matrix A has dimensions (3,3), matrix B has dimensions (2,3)")

In [68]:
length(a5)

9

In [69]:
size(a5)

(3, 3)

In [70]:
ndims(a5)

2

In [71]:
reshape(a5, (9,1))

9×1 Matrix{Int64}:
  5
  7
  1
 10
  8
  2
  3
  6
  3

In [72]:
a5

3×3 Matrix{Int64}:
 5  10  3
 7   8  6
 1   2  3

In [73]:
a5[1,:]

3-element Vector{Int64}:
  5
 10
  3

In [74]:
a5[:,1]

3-element Vector{Int64}:
 5
 7
 1

In [75]:
a5[2]

7

### Diccionarios

In [76]:
d = Dict("Julia" => 2009, "Java" => 1996)

Dict{String, Int64} with 2 entries:
  "Julia" => 2009
  "Java"  => 1996

In [77]:
d["Julia"]

2009

In [78]:
d["C"] = 1972

1972

In [79]:
d["C"]

1972

In [80]:
d["Fortran"]

LoadError: KeyError: key "Fortran" not found

In [81]:
haskey(d, "Fortran")

false

## Control de Flujo

### Expresiones Compuestas

In [82]:
z = begin
           x = 100
           y = 3
           x + y
    end

103

In [83]:
z

103

In [84]:
z = (x = 100; y = 3; x + y)

103

### If

In [85]:
println("x contiene $x, y contiene $y")

x contiene 100, y contiene 3


In [86]:
if x > y
    println("x es menor que y")
end

x es menor que y


In [87]:
if x < y
    println("x es menor que y")
elseif x > y
    println("x es mayor que y")
else
    println("x es igual que y")
end

x es mayor que y


### Operador Ternario

In [88]:
println(x < y ? "x es menor que y" : "x no es menor que y")

x no es menor que y


## While

In [89]:
i = 0
while i <= 5
   println(i)
   i += 1
end

0
1
2
3
4
5


## For

In [90]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [91]:
for i = [1,2,3]
    println(i*2)
end

2
4
6


In [92]:
res = [i^2 for i in [1,2,3]]

3-element Vector{Int64}:
 1
 4
 9

In [93]:
for i in ["Java","Julia","C"]
    println(i)
end

Java
Julia
C
